require:
  - rubocop-performance
  - rubocop-rspec

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 7

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - str_metrics.gemspec

Metrics/AbcSize:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 120

Naming/MethodParameterName:
  AllowedNames:
    - a
    - b
