require:
  - rubocop-performance
  - rubocop-rspec

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 7

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - str_metrics.gemspec

Metrics/ClassLength:
  Max: 120

Naming/MethodParameterName:
  Enabled: true
  Exclude:
    - spec/**/*
